### ISSUE TITLE
Adicionar confirmação no botão 'Close'

### ISSUE THREAD

**Issue by reviewerglobal** [wiz2k20/dataminister#1]
Confirmação com botões **Sim** e **Não** e delay para liberar o botão **Sim**.

**Comment by marciobarcellosdev** [comment]
_in progress_

**Comment by marciobarcellosdev** [comment]
[FIXED] Ao clicar no botão 'Windows > Close' irá mostrar uma caixa de mensagem com os botões YES e NO sendo que o botão YES será habilitado após cinco segundos.

Disponível na build 1012.
